PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    on_warn: fail # Treat all warnings as failures

  TrailingWhitespace:
    enabled: true

  AuthorName:
    enabled: false
