version: '3'
services:
  app:
    build: .
    tty: true
    env_file: .env
    stdin_open: true
    command: make start
    container_name: app
    depends_on:
      - sqs
      - db

  sqs:
    image: roribio16/alpine-sqs:latest
    container_name: sqs
    ports:
      - "9324:9324"
      - "9325:9325"

  db:
    image: postgres:9.6-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
